# This docker-compose file is used to run the application in a local environment
version: "3.9"
services:
  mongo:
    image: mongo
    restart: on-failure
    volumes:
      - './loc/mongodb:/data/db'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    ports:
      - "127.0.0.1:27017:27017"
  mongo-express:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_PASS}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_PASS}
    depends_on:
      - mongo
    ports:
      - "8081:8081"
  gitlab-review-bot:
    image: spatecon/gitlab-review-bot:latest
    depends_on:
      - mongo
    restart: "no"
    volumes:
      - './config/config.yml:/app/config/config.yml'
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=grb
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - GITLAB_TOKEN=${GITLAB_TOKEN}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
