name: DockerHub

on:
  push:
    tags:
      - '*' # Push events to every tag not containing /

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          file: deploy/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/gitlab-review-bot:latest
